(define (div-interval x y)
    (if (and (< x 0) (> y 0))
        (error "division by an interval that spans zero")
        (let ((p1 (* (lower-bound x) (lower-bound y)))
              (p2 (* (lower-bound x) (upper-bound y)))
              (p3 (* (upper-bound x) (lower-bound y)))
              (p4 (* (upper-bound x) (upper-bond y))))
            (make-interval (min p1 p2 p3 p4)
                           (max p1 p2 p3 p4)))))
